require("main.settings")
require("main.keybinds")
require("main.plugins")
require("main.colorscheme")
require("main.cmp")
require("main.lsp")
require("main.telescope")
require("main.treesitter")
require("main.autopairs")
require("main.commenting")
require("main.gitsigns")
require("main.nvim-tree")
require("main.presence-config")
require("main.bufferline")
require("main.lualine")
require("main.toggleterm")
require("main.project")
require("main.impatient")

-- I was too lazy
vim.cmd(":NvimTreeToggle")
